# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mariadb
  RESPONSE_CACHE_ENABLED: "false"

  # Speed up builds
cache:
  key: $CI_BUILD_REF_NAME # changed to $CI_COMMIT_REF_NAME in Gitlab 9.x
  paths:
    - vendor
    - public
test:
  stage: test
  services:
    - mariadb:10.1
  image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine
  script:
    - openssl genrsa -out storage/private.pem -aes256 -passout pass:develop 4096
    - openssl rsa -pubout -in storage/private.pem -passin pass:develop -out storage/public.pem
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    - composer dump-autoload
    - php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: always